spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/campdemo
    driver-class-name: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update