spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/campdemo
    driver-class-name: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    username: campdemo
    password: r00t
  jpa:
    hibernate:
      ddl-auto: create